//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.34209
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bingle.Server {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bingle.Server.ServerResource", typeof(ServerResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   226 ABOR command successful.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AbortOk_226 {
            get {
                return ResourceManager.GetString("AbortOk_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   202 Command ACCT not implemented, superfluous at this site.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AcctOk_220 {
            get {
                return ResourceManager.GetString("AcctOk_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   230 Already logged-in.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AlreadyLoggedIn_230 {
            get {
                return ResourceManager.GetString("AlreadyLoggedIn_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   530 Authentication failed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuthenticationFailed_530 {
            get {
                return ResourceManager.GetString("AuthenticationFailed_530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   504 The security mechanism is not supported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuthError_504 {
            get {
                return ResourceManager.GetString("AuthError_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   234 AUTH Command OK. Initializing {0} connection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AuthOk_234 {
            get {
                return ResourceManager.GetString("AuthOk_234", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 Can&apos;t remove directory {0}. It is a system directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRemoveSystemDirectory_550 {
            get {
                return ResourceManager.GetString("CannotRemoveSystemDirectory_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   553 Can&apos;t rename directory {0}. It is a system directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CannotRenameSystemDirectory_553 {
            get {
                return ResourceManager.GetString("CannotRenameSystemDirectory_553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 Directory changed to {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeDirectoryUp_250 {
            get {
                return ResourceManager.GetString("ChangeDirectoryUp_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 Folder changed to &quot;{0}&quot;.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ChangeWorkDirOk_250 {
            get {
                return ResourceManager.GetString("ChangeWorkDirOk_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   257 &quot;{0}&quot; is current directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentDirectory_257 {
            get {
                return ResourceManager.GetString("CurrentDirectory_257", resourceCulture);
            }
        }
        
        /// <summary>
        ///   150 Connection accepted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DataConnectionAccepted_150 {
            get {
                return ResourceManager.GetString("DataConnectionAccepted_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   420 Can&apos;t open data connection.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DataConnectionCannotOpen_420 {
            get {
                return ResourceManager.GetString("DataConnectionCannotOpen_420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   426 Data connection error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DataConnectionError_426 {
            get {
                return ResourceManager.GetString("DataConnectionError_426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   226 Transfer complete.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DataTransferComplete_226 {
            get {
                return ResourceManager.GetString("DataTransferComplete_226", resourceCulture);
            }
        }
        
        /// <summary>
        ///   450 Can&apos;t delete file {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteFailed_450 {
            get {
                return ResourceManager.GetString("DeleteFailed_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 file deleted.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DeleteOk_250 {
            get {
                return ResourceManager.GetString("DeleteOk_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 {0}: The directory already exists.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DirectoryAlreadyExist_550 {
            get {
                return ResourceManager.GetString("DirectoryAlreadyExist_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   211-Extensions supported:{0}. 211 END과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FeaturesOk_221 {
            get {
                return ResourceManager.GetString("FeaturesOk_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   213 {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileOk_213 {
            get {
                return ResourceManager.GetString("FileOk_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   450 File system error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileSystemError_450 {
            get {
                return ResourceManager.GetString("FileSystemError_450", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 {0}: File unavailable.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FileUnavailable_550 {
            get {
                return ResourceManager.GetString("FileUnavailable_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   220 Welcome SuperSocket FTP Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FTP_Welcome {
            get {
                return ResourceManager.GetString("FTP_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   221 Goodbye.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string GoodBye_221 {
            get {
                return ResourceManager.GetString("GoodBye_221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   551 {0}: Error on input file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InputFileError_551 {
            get {
                return ResourceManager.GetString("InputFileError_551", resourceCulture);
            }
        }
        
        /// <summary>
        ///   501 Syntax error in parameters or arguments.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string InvalidArguments_501 {
            get {
                return ResourceManager.GetString("InvalidArguments_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   230 User logged in, proceed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LoggedIn_230 {
            get {
                return ResourceManager.GetString("LoggedIn_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 Can&apos;t create directory {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MakeDirFailed_550 {
            get {
                return ResourceManager.GetString("MakeDirFailed_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 &quot;{0}&quot; created.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MakeDirOk_250 {
            get {
                return ResourceManager.GetString("MakeDirOk_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   200 Command NOOP okay.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NoopOk_200 {
            get {
                return ResourceManager.GetString("NoopOk_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 No such file or directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotFound_550 {
            get {
                return ResourceManager.GetString("NotFound_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 {0}: No such file or directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotFoundWithPath_550 {
            get {
                return ResourceManager.GetString("NotFoundWithPath_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   502 Command not implemented.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NotImplement_502 {
            get {
                return ResourceManager.GetString("NotImplement_502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   551 Error on output file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OuputFileError_551 {
            get {
                return ResourceManager.GetString("OuputFileError_551", resourceCulture);
            }
        }
        
        /// <summary>
        ///   552 Requested file action aborted. Exceeded storage allocation.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string OutOfStorage_552 {
            get {
                return ResourceManager.GetString("OutOfStorage_552", resourceCulture);
            }
        }
        
        /// <summary>
        ///   227 Entering Passive Mode ({0}).과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PassiveEnter_227 {
            get {
                return ResourceManager.GetString("PassiveEnter_227", resourceCulture);
            }
        }
        
        /// <summary>
        ///   200 Command PBSZ okay.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PBSZ_200 {
            get {
                return ResourceManager.GetString("PBSZ_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 Permission denied.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PermissionDenied_550 {
            get {
                return ResourceManager.GetString("PermissionDenied_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   552 Not a valid port number.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PortInvalid_552 {
            get {
                return ResourceManager.GetString("PortInvalid_552", resourceCulture);
            }
        }
        
        /// <summary>
        ///   220 Command PORT okay.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PortOk_220 {
            get {
                return ResourceManager.GetString("PortOk_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   431 Security is disabled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProtDisabled_431 {
            get {
                return ResourceManager.GetString("ProtDisabled_431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   504 Server does not understand the specified protection level.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProtectionLevelUnknow_504 {
            get {
                return ResourceManager.GetString("ProtectionLevelUnknow_504", resourceCulture);
            }
        }
        
        /// <summary>
        ///   200 Command PROT okay.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProtOk_200 {
            get {
                return ResourceManager.GetString("ProtOk_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   421 Maximum login limit has been reached.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ReachedLoginLimit_421 {
            get {
                return ResourceManager.GetString("ReachedLoginLimit_421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 Can&apos;t remove directory {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveDirectoryFailed_550 {
            get {
                return ResourceManager.GetString("RemoveDirectoryFailed_550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 &quot;{0}&quot; removed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RemoveOk_250 {
            get {
                return ResourceManager.GetString("RemoveOk_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   553 Failed to rename this directory.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameDirectoryFailed_553 {
            get {
                return ResourceManager.GetString("RenameDirectoryFailed_553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   350 Requested file action pending further information.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameForOk_350 {
            get {
                return ResourceManager.GetString("RenameForOk_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   553 Can&apos;t rename file.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameToFailed_553 {
            get {
                return ResourceManager.GetString("RenameToFailed_553", resourceCulture);
            }
        }
        
        /// <summary>
        ///   250 Requested file action okay, file renamed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RenameToOk_250 {
            get {
                return ResourceManager.GetString("RenameToOk_250", resourceCulture);
            }
        }
        
        /// <summary>
        ///   331 Password required for {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RequirePasswor_331 {
            get {
                return ResourceManager.GetString("RequirePasswor_331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   350 Restarting at {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RestartOk_350 {
            get {
                return ResourceManager.GetString("RestartOk_350", resourceCulture);
            }
        }
        
        /// <summary>
        ///   213 {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SizeOk_213 {
            get {
                return ResourceManager.GetString("SizeOk_213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   200 Type set to {0}.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TypeOk_220 {
            get {
                return ResourceManager.GetString("TypeOk_220", resourceCulture);
            }
        }
        
        /// <summary>
        ///   500 Unknown command.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnknownCommand_500 {
            get {
                return ResourceManager.GetString("UnknownCommand_500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   450 Unknown error.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UnknownError_450 {
            get {
                return ResourceManager.GetString("UnknownError_450", resourceCulture);
            }
        }
    }
}
